Web/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using CryptxOnline.Web.AuthorizeService;
using CryptxOnline.Web.Helpers;
using CryptxOnline.Web.Models;
using CryptxOnline.Web.Models.MasterOperation;
using ElFinder.CryptxService;
using NLog;
using WebDav;
using OperationType = ElFinder.CryptxService.OperationType;

namespace CryptxOnline.Web.Controllers
{
    public class MasterController : BaseController
    {
        private readonly Logger _logger = LogManager.GetCurrentClassLogger();

        public ActionResult Index(string files, OperationType? type)
        {
            //List<ElFinder.WebDav.File> Files;
            //try
            //{
            //    var js = new JavaScriptSerializer();
            //    Files = js.Deserialize<List<ElFinder.WebDav.File>>(files);
            //}
            //catch{}

            Guid token = CheckSessionAuthState(CurrentUser, _authService);
            if (token == Guid.Empty)
            {
                return RedirectToAction("LogOff", "Account");
            }
            var masterModel = new MasterInitModel(token, _cryptxService, _authService, files, type);
            ViewBag.masterModel = masterModel;
            //ViewBag.Debug = (Convert.ToBoolean(Request.Params["debug"]) == true).ToString().ToLower();

            return View("Index");
        }

        /// <summary>
        ///     Получение профиля по ID
        /// </summary>
        /// <param name="profileId"></param>
        /// <returns></returns>
        public ActionResult GetUserProfile(Guid profileId)
        {
            Guid token = CheckSessionAuthState(CurrentUser, _authService);
            if (token == Guid.Empty)
            {
                return Json(new { status = "Error", errorCode = "401", errorMessage = "" }, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("LogOff", "Account");
            }
            ProfileResponse response = _cryptxService.GetProfile(profileId, Guid.Empty, token);
            if (response.Exception != null)
            {
                throw response.Exception;
            }
            return Json(response.Settings, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///     Получение списка личных сертификатов
        /// </summary>
        /// <returns></returns>
        public ActionResult GetMyCertificates()
        {
            Guid token = CheckSessionAuthState(CurrentUser, _authService);
            if (token == Guid.Empty)
            {
                return Json(new { status = "Error", errorCode = "401", errorMessage = "" }, JsonRequestBehavior.AllowGet);
            }
            //bool isActiveCur = isActive ?? false;

            var model = new List<CertificateInfoContactAdd>();
            CertificatesResponse response = _cryptxService.GetMyCertificates(Guid.Empty, token);
            if (response.Exception == null)
            {
                foreach (CertificateInfo certificateInfo in response.Certificates)
                {
                    var curCert = new CertificateInfoContactAdd();
                    curCert.CertificateId = certificateInfo.CertificateId;
                    curCert.SubjectName = certificateInfo.SubjectName;
                    curCert.IssureName = certificateInfo.IssureName;
                    curCert.Thumbprint = certificateInfo.Thumbprint;
                    curCert.Organization = certificateInfo.Organization;
                    curCert.IsTest = certificateInfo.IsTest;
                    if (DateTime.Now < certificateInfo.NotBefore)
                    {
                        curCert.TimeMessage = "Недействителен до " +
                                              certificateInfo.NotBefore.Date.ToShortDateString().Replace("/", ".");
                    }
                    if (DateTime.Now > certificateInfo.NotBefore && DateTime.Now < certificateInfo.NotAfter)
                    {
                        curCert.TimeMessage = "Действителен до " +
                                              certificateInfo.NotAfter.Date.ToShortDateString().Replace("/", ".");
                    }
                    else
                    {
                        curCert.TimeMessage = "Недействителен с " +
                                              certificateInfo.NotAfter.Date.ToShortDateString().Replace("/", ".");
                    }
                    model.Add(curCert);
                }
            }
            else
            {
                return Json(new { status = "Error", errorCode = "", errorMessage = response.Exception.Message },
                    JsonRequestBehavior.AllowGet);
            }

            return Json(new { model, status = "ok" }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///     Запрос на поиск сертов
        /// </summary>
        /// <param name="isActive"></param>
        /// <param name="searchString"></param>
        /// <returns></returns>
        public ActionResult FindCertificate(bool isActive = false, string searchString = "")
        {
            Guid token = CheckSessionAuthState(CurrentUser, _authService);
            if (token == Guid.Empty)
            {
                return Json(new { status = "Error", errorCode = "401", errorMessage = "" }, JsonRequestBehavior.AllowGet);
            }
            //bool isActiveCur = isActive ?? false;

            var model = new List<CertificateInfoContactAdd>();
            SearchResultResponse response = _cryptxService.GetCertificatesBySearchString(searchString, isActive, false,
                token);
            if (response.Exception == null)
            {
                foreach (CertificateInfo certificateInfo in response.Certificates)
                {
                    var curCert = new CertificateInfoContactAdd();
                    curCert.CertificateId = certificateInfo.CertificateId;
                    curCert.SubjectName = certificateInfo.SubjectName;
                    curCert.IssureName = certificateInfo.IssureName;
                    curCert.Thumbprint = certificateInfo.Thumbprint;
                    curCert.Organization = certificateInfo.Organization;
                    curCert.IsTest = certificateInfo.IsTest;
                    if (DateTime.Now < certificateInfo.NotBefore)
                    {
                        curCert.TimeMessage = "Недействителен до " +
                                              certificateInfo.NotBefore.Date.ToShortDateString().Replace("/", ".");
                    }
                    if (DateTime.Now > certificateInfo.NotBefore && DateTime.Now < certificateInfo.NotAfter)
                    {
                        curCert.TimeMessage = "Действителен до " +
                                              certificateInfo.NotAfter.Date.ToShortDateString().Replace("/", ".");
                    }
                    else
                    {
                        curCert.TimeMessage = "Недействителен с " +
                                              certificateInfo.NotAfter.Date.ToShortDateString().Replace("/", ".");
                    }
                    model.Add(curCert);
                }
            }
            else
            {
                return Json(new { status = "Error", errorCode = "", errorMessage = response.Exception.Message },
                    JsonRequestBehavior.AllowGet);
            }

            return Json(new { model, status = "ok" }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///     Получение информации по сертификату
        /// </summary>
        /// <param name="thumbprints"></param>
        /// <returns></returns>
        public ActionResult GetCertificatesInfo(List<string> thumbprints)
        {
            Guid token = CheckSessionAuthState(CurrentUser, _authService);
            if (token == Guid.Empty)
            {
                return Json(new { status = "Error", errorCode = "401", errorMessage = "" }, JsonRequestBehavior.AllowGet);
            }
            var certificates = new List<CertificateInfo>();
            foreach (string thumbprint in thumbprints)
            {
                CertificateResponse response = _cryptxService.GetCertificate(thumbprint, Guid.Empty, token);
                certificates.Add(response.Certificate);
            }


            return Json(new { certificates }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///     Получение нулевого профиля
        /// </summary>
        /// <returns></returns>
        public ActionResult GetBlankProfile()
        {
            Guid token = CheckSessionAuthState(CurrentUser, _authService);
            if (token == Guid.Empty)
            {
                return Json(new { status = "Error", errorCode = "401", errorMessage = "" }, JsonRequestBehavior.AllowGet);
            }
            ProfileResponse response = _cryptxService.GetBlankProfile();
            if (response.Exception == null)
            {
                return Json(new { response.Settings }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { status = "Error", errorCode = "401", errorMessage = response.Exception.Message },
                JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///     Проверка подписанного файла на отсоединенность подписи
        /// </summary>
        /// <param name="signedFileInfosJSON"></param>
        /// <returns></returns>
        public ActionResult CheckSignedFilesAtachment(string signedFileInfosJSON)
        {
            Guid token = CheckSessionAuthState(CurrentUser, _authService);
            if (token == Guid.Empty)
            {

Web/Views/Shared/JsGlobal.cshtml
@using System.Web.Optimization

<script type="text/javascript">
	var Crypt = Crypt || {};
	Crypt.Urls = {
		KobilLogin: '@Url.Action("KobilLogin","Account")',
		LoginGuid: '@Url.Action("LoginGuid", "Account")',
		CheckKobil:	'@Url.Action("CheckKobil", "Account")',
		Login: '@Url.Action("Login", "Account")',
		CancelKobil: '@Url.Action("CancelKobil", "Account")',
		CheckSmsPin: '@Url.Action("CheckSmsPin", "Account")',
		ResendSms: '@Url.Action("ResendSms", "Account")',
        CheckPhoneNEmail: '@Url.Action("CheckPhoneNEmail", "Registration")',
		SmsConfirmReg: '@Url.Action("SmsConfirmation", "Registration")',
		ResendSmsReg: '@Url.Action("ResendSms", "Registration")',
        Profile: '@Url.Action("MyProfile", "Default")',
        CertList: {
            ChangePin: '@Url.Action("ChangePin")',
            DeletePin: '@Url.Action("DeletePin")',
            SetPin: '@Url.Action("SetPin")',
            SaveCertFriendlyName: '@Url.Action("SaveCertFriendlyName")'
        },
        CreateTestCertificate: '@Url.Action("GetNSetTestCertificate","MarkerActivation")',
        SendToSupport: '@Url.Action("SendToSupport","BaseAnonymous")',

        MarkerLogon: '@Url.Action("Logon","MarkerActivation")',
        MarkerCertInfo: '@Url.Action("GetCertificateInfo","MarkerActivation")',
        MarkerRequestCertInfo: '@Url.Action("GetCertificateInfoConfirmedRequest","MarkerActivation")',
        MarkerResendSms: '@Url.Action("ResendSms","MarkerActivation")',
        MarkerCheckSms: '@Url.Action("CheckSms","MarkerActivation")',
        MarkerSendRequest: '@Url.Action("CreateCertificateRequest","MarkerActivation")',
        MarkerRequestResend: '@Url.Action("ResendRequest","MarkerActivation")',
        MarkerRequestResendAgain: '@Url.Action("ResendRequestAfterCheckSms","MarkerActivation")',
        MarkerRequestConfirm: '@Url.Action("GetNSetCertificate","MarkerActivation")',
        MarkerRequestDelete: '@Url.Action("DeleteRequest","MarkerActivation")',
        MarkerRequestGetData: '@Url.Action("GetRequestData","MarkerActivation")'

	}
</script>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title</title>
        <meta name="format-detection" content="telephone=no" />
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Assets/libjs/jquery-2.1.0.min.js")" type="text/javascript"></script>
        <link href="@Url.Content("~/Content/kendo.common.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/kendo.metro.min.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Assets/libjs/kendo.web.min.js")" type="text/javascript"></script>

    </head>

    <body>
        @if (@ViewContext.RouteData.Values["action"].ToString() != "Login")
        {
            <div id="header">
                <table style="width: 100%">
                    <tr>
                        <td style="padding-left: 30px; width: 200px;">
                            <a href="@Url.Action("Index", "Default")"> <img border="0" class="main-img" src="@Url.Content("~/Assets/i/old/main_logo.png")" /></a>
                        </td>
                        <td style="font-size: 30px; margin-bottom: 0px; vertical-align: bottom">
                            CryptX Online
                        </td>

                        <td>
                            @*                        @if (Request.Cookies[".DSSAUTH"] != null)
                            {
                                @Html.ActionLink("Мастер подписи", "Index", "Wizard", new {type = 1}, new {})<a>&nbsp</a>
                                @Html.ActionLink("Мастер шифрования", "Index", "Wizard", new {type = 2}, new {})
                            }*@
                        </td>
                        <td style="padding-right: 10px; text-align: right; vertical-align: central;">

                            @if (Request.Cookies[".DSSAUTH"] != null)
                            {
                                if (!(@ViewContext.RouteData.Values["action"].ToString() == "Index" && @ViewContext.RouteData.Values["controller"].ToString() == "Default"))
                                {
                                }
                                if (ViewBag.login != null)
                                {
                                    <a>Вы авторизованы как</a>
                                    <a style="font-size: 16px; font-style: italic; padding-right: 20px"><b>@ViewBag.login</b> &nbsp;</a>
                                }
                                <button class="button" onclick=" location.href = '@Url.Action("LogOff", "Account")';return false; ">Выход</button>
                            }

                        </td>
                    </tr>
                </table>
            </div>
        }
        else
        {
            <div id="header">
                <table style="text-align: left; width: 100%;">
                    <tr>
                        <td style="padding-left: 30px; width: 200px;">
                            <a href="@Url.Action("Index", "Default")"> <img border="0" class="main-img" src="@Url.Content("~/Assets/i/old/main_logo.png")" /></a>
                        </td>
                        <td style="font-size: 30px; margin-bottom: 0px; vertical-align: bottom">
                            CryptX Online
                        </td>

                    </tr>
                </table>
            </div>
        }
        @if (!((@ViewContext.RouteData.Values["action"].ToString() == "Login" && @ViewContext.RouteData.Values["controller"].ToString() == "Default") || (@ViewContext.RouteData.Values["action"].ToString() == "Index" && @ViewContext.RouteData.Values["controller"].ToString() == "Error")))
        {
            <div class="certs-panel center-panel">
                <table style="width: 100%">
                    <tr>
                        <td style="vertical-align: top; width: 15%">
                            <table style="margin-left: 10px">
                                <tr>
                                    <td>
                                        @Html.ActionLink("Мои сертификаты", "MyCertificates", "Default")
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @Html.ActionLink("Сертификаты контрагентов", "RecipientCertificates", "Default")
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding-bottom: 15px">
                                        @Html.ActionLink("Профили пользователя", "Profiles", "Default")
                                    </td>
                                </tr>


                                <tr>
                                    <td style="background-color: gray"></td>
                                </tr>
                                <tr>
                                    <td style="padding-top: 10px">
                                        @Html.ActionLink("Мастер", "Index", "Master")
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding-top: 10px">
                                        @Html.ActionLink("Мастер подписи", "Index", "Wizard", new {type = 1}, new {})
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @Html.ActionLink("Мастер проверки подписи", "Index", "Wizard", new {type = 4}, new {})
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @Html.ActionLink("Мастер шифрования", "Index", "Wizard", new {type = 2}, new {})
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @Html.ActionLink("Мастер расшифровки", "Index", "Wizard", new {type = 3}, new {})
                                    </td>
                                </tr>
                            </table>

                        </td>
                        <td>
                            @RenderBody()
                        </td>
                    </tr>
                </table>
            </div>
        }
        else
        {
            @RenderBody()
        }
        @*@Scripts.Render("~/bundles/jquery")*@
        @RenderSection("scripts", false)
    </body>
</html>

Web/Views/Shared/_LayoutCleanSheet.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div>
            @RenderBody()
        </div>
    </body>
</html>

Web/Views/Shared/_LayoutMaster.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html>
    <head>

        <meta charset="utf-8" />
        <meta name="format-detection" content="telephone=no" />
        @Scripts.Render("~/Assets/libjs/jquery-2.1.3.js")
        @Scripts.Render("~/Assets/libjs/can/2.1.2/can.custom.js")
        @Scripts.Render("~/Assets/libjs/moment/moment.min.js")
        @Scripts.Render("~/Assets/js/master.js")
        @Scripts.Render("~/Assets/libjs/bootstrap/dropdown.js")
        @Scripts.Render("~/Assets/libjs/keypress/keypress.min.js")
        @Scripts.Render("~/Assets/libjs/Login/baron.min.js")
        @Scripts.Render("~/Assets/libjs/plupload/plupload.full.min.js")
        @Scripts.Render("~/Assets/libjs/newJS/jquery.fancybox.pack.js")

        <script src="/Assets/libjs/opentip.js"></script>

        <link href="/Assets/css/opentip.css" rel="stylesheet" />
        <link href="@Url.Content("~/Assets/css/master.css")" rel="stylesheet" type="text/css" media="all" />

        <link href="@Url.Content("~/Assets/i/old/favicon.ico")" rel="shortcut icon" type="image/x-icon" />

        <script type="text/javascript">
            Master = {};
            $(function() {
                Master = new InitMaster({
                    tag: 'body',
                    templates: {
                        all: @Html.Raw(ViewBag.masterModel.SettingsJSON),
                        'default': @Html.Raw(ViewBag.masterModel.BlankProfileJSON)
                    },
                    urlUpload: '@Url.Action("GetFile", "Master")',
                    user: {
                        name: '@ViewBag.masterModel.UserInfo.Name',
                        isAdmin: @((CurrentUser.IsInRole("GroupAdmin") || CurrentUser.IsInRole("SysAdmin")).ToString().ToLower())
                    },
                    initialize: {
                        files: @Html.Raw(ViewBag.masterModel.FilesJSON),
                        type: '@ViewBag.masterModel.OperationType'
                    },
                    lang: 'ru',
                    debug: false
                });
            });
        </script>

        <title>Мастер</title>
    </head>
    <body>
        @RenderBody()
    </body>
</html>

Web/Views/Shared/_LayoutPassRecovery.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>

	<meta charset="UTF-8" />
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

	<meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link href="/Assets/i/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link href="/Assets/css/restore.css?v=@AssetsVersion" rel="stylesheet"/>

	<script src="//yandex.st/jquery/1.8.0/jquery.min.js"></script>
	<script src="/Assets/libjs/newJS/modernizr.js"></script>
	<script src="/Assets/libjs/newJS/respond.js"></script>
	<script src="/Assets/libjs/newJS/bootstrap.min.js"></script>
	<script src="/Assets/libjs/newJS/baron.min.js"></script>
	<script src="/Assets/libjs/newJS/jquery.fancybox.pack.js"></script>
	<script src="/Assets/libjs/newJS/cusel.min.js"></script>
	<script src="/Assets/libjs/newJS/bootstrap-checkbox.js"></script>
	<script src="/Assets/libjs/jquery/jquery.maskedinput.min.js"></script>
	<script src="/Assets/libjs/newJS/script.js"></script>

	@Scripts.Render("~/Assets/libjs/can/2.1.2/can.custom.js")

	@RenderSection("scriptControl", false)



    <!--[if IE 8]>
        <link href="/Assets/css/ie.css?v=@AssetsVersion" rel="stylesheet"/>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"> </script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"> </script>
    <![endif]-->
</head>
<body>
<div id="container">
	<div id="header">
		<div class="logo col">
			<a href="/">
				CRYPTOGRAMM
			</a>
		</div>
	</div>
	@RenderBody()
</div>
</body>
</html>

Web/Views/Shared/_LayoutWizardPage.cshtml
@using CryptxOnline.Web.Helpers
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <meta name="format-detection" content="telephone=no" />
        <title>@ViewBag.Title</title>
        <script src="/Assets/libjs/jquery-2.1.0.js"></script>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/kendo.common.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/kendo.metro.min.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Assets/libjs/kendo.web.min.js")" type="text/javascript"></script>
        <link href="@Url.Content("~/Content/Wizard.css")" rel="stylesheet" type="text/css" />

    </head>
    <body>
        @if (ViewBag.page != "login")
        {
            <div id="header">
                <table style="width: 100%">
                    <tr>
                        <td style="padding-left: 30px; width: 200px;">
                            <a href="@Url.Action("Index", "Default")"> <img border="0" class="main-img" src="@Url.Content("~/Assets/i/old/main_logo.png")" /></a>
                        </td>
                        <td style="font-size: 30px; margin-bottom: 0px; vertical-align: bottom">
                            CryptX Online
                        </td>

                        <td>
                            @*                        @if (Request.Cookies[".DSSAUTH"] != null)
                            {
                                @Html.ActionLink("Мастер подписи", "Index", "Wizard", new {type = 1}, new {})<a>&nbsp</a>
                                @Html.ActionLink("Мастер шифрования", "Index", "Wizard", new {type = 2}, new {})
                            }*@
                        </td>
                        <td style="padding-right: 10px; text-align: right; vertical-align: central;">

                            @if (Request.Cookies[".DSSAUTH"] != null)
                            {
                                if (!(@ViewContext.RouteData.Values["action"].ToString() == "Index" && @ViewContext.RouteData.Values["controller"].ToString() == "Default"))
                                {
                                    //@Html.ActionLink("На главную", "Index", "Default")
                                }
                                <a>Вы авторизованы как</a>
                                <a style="font-size: 16px; font-style: italic; padding-right: 20px"><b>@ViewBag.login</b> &nbsp;</a>
                                <button class="button" onclick=" location.href = '@Url.Action("LogOff", "Account")';return false; ">Выход</button>
                            }
                        </td>
                    </tr>
                </table>
            </div>
        }
        else
        {
            <div id="header">
                <table style="text-align: left; width: 100%;">
                    <tr>
                        <td style="font-size: 30px; width: 200px">
                            <img src="@Url.Content("~/Assets/i/old/main_logo.png")" /> CryptX Online
                        </td>
                    </tr>
                </table>
            </div>
        }
        <table class="wizard-main">
            <tr>
                <td class="wizard-menu">
                    <a style="font-size: 20px; font-weight: bold;">@ViewBag.WizardName</a>
                    <table style="padding-left: 10px">
                        @foreach (CustomWizardStep act in ViewBag.WizardSteps)
                        {
                            <tr>
                                @if (@ViewContext.RouteData.Values["action"].ToString() == act.Step)
                                {
                                    <td class="curr">
                                        @Html.Label(act.StepText)
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        @Html.Label(act.StepText)
                                    </td>
                                }
                            </tr>
                        }
                    </table>
                </td>
                <td class="wizard-panel">
                    @RenderBody()
                </td>
                @RenderSection("scripts", false)
            </tr>
        </table>
    </body>
</html>

Web/Views/Shared/jQuery.cshtml
@using System.Web.Optimization

<!--[if (!IE)|(gt IE 8)]><!-->
    <script src="/Assets/libjs/jquery-2.1.3.min.js"></script>
    <script src="/Assets/libjs/Lib/jquery/jquery-migrate-1.2.1.js"></script>
<!--<![endif]-->

<!--[if lte IE 8]>
    <script src="/Assets/libjs/jquery-1.9.1.min.js"></script>
<![endif]-->